version: '3.7'

services:
  fee-track:
    container_name: track-blochain-fee
    build:
      context: .
    restart: unless-stopped
    networks:
      - trackblockchainfee-network

networks:
  trackblockchainfee-network: