services:
  fee-track:
    container_name: track-blockchain-fee
    build:
      context: .
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      - trackblockchainfee-network
    volumes:
      - ./logs:/logs
  redis:
    image: redis:7.4-alpine
    container_name: blockchain-fee-redis
    restart: always
    ports:
      - '6379:6379'
    volumes: 
      - redis:/data
    networks:
      - trackblockchainfee-network
networks:
  trackblockchainfee-network:
volumes:
  redis:
    driver: local